### ISSUE TITLE
Projector: Permission change

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-autoupdate-service#1011]
**Current behavior**
Currently, with the group right “Can see the projector”, you can see the projector in the Autopilot and the menu item “Projector”. The last point is suboptimal, as A) the menu item potentially contains further administrative content that should not be publicly visible and B) the menu bar generally contains an item that offers no added value for following a meeting.

**Wanted behavior**
The group right 'Can see the projector' should only make the projector visible in Autopilot, no longer the menu item 'Projector'. The menu item should only be visible via the 'Can manage the projector' group right.  

Important: The content currently projected onto the standard projector should still be visible in the Autopilot. No changes should be made in the Autopilot.

**Comment by ostcar** [comment]
@rrenkert when you say "default projector" you probably mean "reference projector"? 
We have the fields [used_as_reference_projector_meeting_id](https://github.com/OpenSlides/openslides-meta/blob/8e7451440fae5aa809e3d828b6552c7f0e7feb3d/models.yml#L3982) and we have fields [used_as_default_projector_for_*_in_meeting_id](https://github.com/OpenSlides/openslides-meta/blob/8e7451440fae5aa809e3d828b6552c7f0e7feb3d/models.yml#L3986-L4041)

Are you sure, that only the projector has to be changed and not also the projection?

**Comment by bastianjoel** [comment]
The projections also need to be changed.

**Comment by ostcar** [comment]
> The projections also need to be changed.

How should it change? The current rule is:
> The user can see a projection, if the user has projector.can_see.

This means, even before this change, that a user could see a projection of a projector, when the projector was set to internal. Was this intended? If not, then I would propose, that a user can see a projection, if he can see the linked projector. This would mean, that a user with `meeting.can_see_autopilot` can see the projection on the reference projector, but to see projections on other projectors, you need `projector.can_see`. In the projector is internal, then you need `projector.can_manage`, and it does not mater, ifs the reference projector or not.

Is this ok?

**Comment by bastianjoel** [comment]
Sounds good. The client only ever requests projections via projectors so this should not break anything.
