### ISSUE TITLE
New gender model

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-autoupdate-service#1023]
The client and the backend have a new model for the genders
it appears that the autoupdate needs to implement the new collection.

  >            The autoupdate service gives following:
>Error: getting next message: creating first time data: create keys for
keysbuilder: load needed keys: restricting data: getting restiction mode for
gender/A: collection "gender" is not implemented, maybe run go generate ./...
to fetch all fields from the models.yml

> I suppose that the autoupdate service needs to implement the new 'gender' collection in the restrictor.
Running go generate doesn't help-

_Originally posted by @reiterl in https://github.com/OpenSlides/openslides-client/issues/4027#issuecomment-2363297729_
            

The new gender: 
- The Gender stays optional for the user (you are allowed to give no gender at all) 
- the four base genders (male, female, diverse, non-binary) are the default genders
- the default genders cannot be deleted 
- new additional genders can be created
- The name of new genders can be changed and they can be deleted
- genders are now called via the gender_ids

Please look into the changed in models.yml and the action in the respective PRs
https://github.com/OpenSlides/openslides-meta/pull/116/files
https://github.com/OpenSlides/openslides-backend/pull/2485/files

**Comment by ostcar** [comment]
I created a PR

When should a user see the gender collection? For the start, I set it to always. So every buddy, even anonymous, can see all genders.
