### ISSUE TITLE
OPENSLIDES_PUBLIC_ACCESS_ONLY_MODE

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-autoupdate-service#1047]
I was thinking about renaming
`ANONYMOUS_ONLY`
to
  `OPENSLIDES_PUBLIC_ACCESS_ONLY` or
  `OPENSLIDES_PUBLIC_ACCESS_ONLY_MODE`.

As the search service also already uses this variable (and there might be even more in the future) I think it is appropriate to prefix with `OPENSLIDES_` to indicate it's accepted not just by one service, similar to e.g. `OPENSLIDES_LOG_LEVEL`.

Also I think `OPENSLIDES_PUBLIC_ACCESS_ONLY_MODE=1` should also implicate connections to the DB only be made in read-only mode.

**Comment by peb-adr** [comment]
@rrenkert @ostcar FYI / thoughts?

**Comment by ostcar** [comment]
Yea. Let's do it.
