### ISSUE TITLE
Internal error on normal relations

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#109]
Hi, I am currently testing the new structured fields. This request should trigger the error: The actual request was longer, but this is the part that is interesting I think. If it does work, I can provide you with a full request.

```
{"collection": "meeting", "ids": [1], "fields": {"default_group_id": {"collection": "group", "fields": {"name": null, "id": null}, "type": "relation"}}}
```

```
Internal Error: build keysbuilder: build keys: build keys for the first time: load needed keys: restrict data: checker for key meeting/1/default_group_id: decoding meeting/1/default_group_id=1: json: cannot unmarshal number into Go value of type []int
```

**Comment by ostcar** [comment]
Thx for this bug report. There was an ugly bug. All relation fields were handled as relation-list fields
