### ISSUE TITLE
Auth token failed to decode

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#122]
Hi,

on the current master:
```
Internal Error: authenticate request: reading token: validating auth cookie: token is malformed: failed to decode token header
```

This is the header:
```
authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiIxMG0iLCJzZXNzaW9uSWQiOiIxMWY0MWNmOWI5ZDYzMmUxODQwYzZlNzUxMGY3OTFiZCIsInVzZXJJZCI6MSwiaWF0IjoxNjAzOTY3Mzc5LCJleHAiOjE2MDM5Njc5Nzl9.3G7PZAy0nVMLPnyeoYJHsuTivZY7QZeHxJJEoL9__Bo
```

Cookies:
```
cookie: OpenSlidesCsrfToken=lDkDxdbISHYFZFYOJmmX0NeOVv9jd65mVXRpgkug7kOApPHCUNVw5oQ6eqVoQQ6y; OpenSlidesSessionID=fe4zf3r8v4x4ttf5wisns6iarcfauexj; refreshId=bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiIxMWY0MWNmOWI5ZDYzMmUxODQwYzZlNzUxMGY3OTFiZCIsImlhdCI6MTYwMzk2NzM3NSwiZXhwIjoxNjA0MDUzNzc1fQ.73SdXPGyRlwVud4lBpcUWlewvfXZdBB9v84nzhWoLiU
```

Again, please try your changes with the complete dev setup; I still try to merge the structured field rework, but get stuck on things like this.

**Comment by ostcar** [comment]
I try to test the complete dev setup as soon as possible.

In this case, It seems to be a problem with the auth serivce. The autoupdate-service expect the dev-auth-keys to be the string `auth-dev-key` It seems, the current version of the auth-service still uses the content of the rsa key:  https://github.com/OpenSlides/openslides-auth-service/blob/bb90ce7366be8691a0106f80816dbdbb73d22ecb/auth/src/config/index.ts#L20

**Comment by FinnStutzenstein** [comment]
Than for further use please wait when merging - I cannot work with non-matched services. Or do you have a commit where structured fields work and the auth is unchanged?

**Comment by ostcar** [comment]
You can deactivate the auth Service. Use the environment variable

AUTH=fake

I set this variable to ticket in the dockerfile. The default is fake and always uses the uid 1.

**Comment by ostcar** [comment]
Can this be closed?
