### ISSUE TITLE
Provide a default message

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#152]
If "anonymous=0" the autoupdate-service send messages to a client. The client's operator does not load and a user will see only a white page.
Therefore, please provide a default message, that the operator loads and redirects a user to a login-page.

**Comment by ostcar** [comment]
I don't understand what you mean. With ànonymous=0` you mean, that the request user is anonymous?

What do you mean with a default message? The return value is a json-dictonary. If it is empty, the service returns `{}`. Can't you use this als default message?

Another solution is, that the client always ask for keys, that are not restricted by the permission service. For example `organisation/1/id` or `meeting/X/enable_anonymous`.

**Comment by FinnStutzenstein** [comment]
Gabriel: I also discovered this issue, that the client didn't load. I resolved it during the rebase I think. Please check again.

**Comment by GabrielInTheWorld** [comment]
> Gabriel: I also discovered this issue, that the client didn't load. I resolved it during the rebase I think. Please check again.

Yeah, it's fixed. Thanks!
