### ISSUE TITLE
Calculate title information

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-autoupdate-service#174]
The `list_of_speakers`slide needs a function to render the title_information. This depence on the content_object.

**Comment by ostcar** [comment]
@r-peschke I this this can be closed.

**Comment by r-peschke** [comment]
> @r-peschke I this this can be closed.
There is no GetTitleInformation-function registered for the one of the 3 speaker-lists, but they all present a speaker list from user.GetRepresentation.
The titleInformation for the speaker list itself is only a string `"title_information for %s", los.ContentObjectID`. Regarding the wiki for this slider, we should provide a title information from the content_object_id for the speaker list.
I think I will do that and we shouldn't close the Issue.
