### ISSUE TITLE
assignment slide

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-autoupdate-service#177]

**Comment by FinnStutzenstein** [comment]
The candidates should be a list of strings, currently it is a list of objects.

@r-peschke Can you do this?

**Comment by FinnStutzenstein** [comment]
Also `phase`, `open_posts` are removed from the slidedata.

**Comment by FinnStutzenstein** [comment]
The two fields are still TODO. If those are removed, this issue can be closed and the slide is finished.
