### ISSUE TITLE
Cannot get keys for `organization_tags`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#227]
```
autoupdate_1        | 2021/06/14 11:10:56 Internal Error: getting keys: get all keys: create keys for keysbuilder: load needed keys: restrict data: checker for key organization/1/organization_tag_ids: check fqids: unknown collection: `organization_tag`
```

If you need more information, please contact me.

**Comment by ostcar** [comment]
@FinnStutzenstein is this related to #221?

**Comment by FinnStutzenstein** [comment]
I think not, orga tags are fairly new, maybe they are missing completly.

**Comment by ostcar** [comment]
@FinnStutzenstein you are right. The permission-package does not know the organization_tag collection.

I don't understand this wiki-page: https://github.com/OpenSlides/OpenSlides/wiki/organization_tag-restrictions

Is it correct, that every logged in user can see every field of the collection? I am not sure if you have to be logged in to see the ID-Field or if anonyous can see the id field (see my mail).

**Comment by FinnStutzenstein** [comment]
YOu have to be logged in to see the collection.
