### ISSUE TITLE
CLOS slide error

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#233]
`Error parsing slide projection/3/content: calculating slide: fetching user/3/list_of_speakers_id: user/3/list_of_speakers_id does not exist.`

This is what I get when projecting a user and having a CLOS projected. This is due to the example data where a CLOS is projected by default:

https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/example-data.json#L2674

Can you please disable this slide until it fully works by returning `{}` or so?

**Comment by ostcar** [comment]
The CLOS should work. I have a look of I can reproduce your error.

Maybe your should change the example data for Wednesday.

**Comment by ostcar** [comment]
@FinnStutzenstein There where a lot of fixes. I would propose that you check again next week if the error still happens.
