### ISSUE TITLE
Users with `OML.can_manage_users` can see committees

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#234]
Previously, users only with the OML `can_manage_organization` or higher (or included in `committee/user_ids`) could see committees.
Now, users with the OML `can_manage_users` or higher can see committees to assign/unassign users to committees.
Please update.

**Comment by ostcar** [comment]
@FinnStutzenstein @normanjaeckel 

In which cases is the permission  can_manage_organization still be used? Can it be removed at all?

**Comment by FinnStutzenstein** [comment]
It is used for restricting `committee/forward_to_committee_ids` (and the reverse relation). See https://github.com/OpenSlides/OpenSlides/wiki/committee-restrictions
