### ISSUE TITLE
Cannot receive committees if not superadmin

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#242]
Fresh example data. Logged in as user 2 (a). Request:

```
{
  "collection": "organization",
  "ids": [
    1
  ],
  "fields": {
    "id": null,
    "committee_ids": {
      "type": "relation-list",
      "collection": "committee",
      "fields": {
        "name": null,
        "description": null,
        "meeting_ids": null,
        "forward_to_committee_ids": null,
        "receive_forwardings_from_committee_ids": null,
        "organization_tag_ids": {
          "type": "relation-list",
          "collection": "organization_tag",
          "fields": {
            "color": null,
            "name": null,
            "committee_ids": null,
            "organization_id": null,
            "id": null
          }
        },
        "user_ids": {
          "type": "relation-list",
          "collection": "user",
          "fields": {
            "title": null,
            "first_name": null,
            "last_name": null,
            "username": null,
            "id": null
          }
        },
        "id": null
      }
    }
  }
}
```
Autoupdate:
```
{
  "organization/1/committee_ids": [],
  "organization/1/id": 1
}
```

I expect the user 2 to get committee 1 since the user is a member of the committee.

**Comment by ostcar** [comment]
I am looking for the field user/committee_as_member
 https://github.com/OpenSlides/openslides-autoupdate-service/blob/b5ec9c6f9ed429441343e3273559ac4904b17d0c/internal/restrict/permission/tests/testcases/committee/read.yml#L40

But it seems, that this field does not exist in the models.yml or example-data.

Did the models.yml change?

How can I find out, if a user is a member of a committee?

**Comment by FinnStutzenstein** [comment]
> Did the models.yml change?

This was changed more than two month ago

> How can I find out, if a user is a member of a committee?

https://github.com/OpenSlides/OpenSlides/wiki/Users#user-association-to-committees

**Comment by ostcar** [comment]
@FinnStutzenstein could you check if the [wiki page](https://github.com/OpenSlides/OpenSlides/wiki/committee-restrictions) is outdated? see: #234

What is the correct place for issues in the wiki?

**Comment by ostcar** [comment]
Sry. Misread the page...
