### ISSUE TITLE
Unlimited reconnection attempts when user in `default`-group

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#243]
Signing in as a user in the default-group of one meeting (in a meeting) leads to unlimited reconnection attempts to the autoupdate-service.
This has to be investigated.

**Comment by ostcar** [comment]
The error message says, that the field motion_comment_section/1/motion_id does not exist. I also can not find this field in the models.yml or example data

https://github.com/OpenSlides/OpenSlides/blob/610a10712d1194fd56387da07fbc2bac924479b7/docs/example-data.json#L1572

https://github.com/OpenSlides/OpenSlides/blob/610a10712d1194fd56387da07fbc2bac924479b7/docs/models.yml#L1443

Did the models.yml change? Did you inform me? I thought we agreed that a pr that changes the models.yml has to wait until all maintainer changed there services and approved the change.

**Comment by FinnStutzenstein** [comment]
No, this field never existed before since comment sections do not directly link to motions at all.

**Comment by ostcar** [comment]
Ok. I fixed this issue in the autoupdate-service.

But maybe you should also change the client. If there is a 500er on the server and the client will try to reconnect constantly, then it would ddos the server.

Maybe retry 3 times, and once more after a minute but then stop with an error message viable to the user.
