### ISSUE TITLE
No autoupdates for the projector

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#244]
Sometimes after 10 secs, but e.g. for topics: Changing the topic title does not issue any autoupdates, not even after 10 secs.

**Comment by ostcar** [comment]
I would like to understand this bug.

Is it only the projector or are there other fields that also do not update?

Are there any log messages?

If it happens, does it help to reload the page (reconnect) or do you have to restart the autoupdate service?

Do you have a way how I could reproduce it?

**Comment by GabrielInTheWorld** [comment]
I think, this is a bug in the client. See OpenSlides/openslides-client#358

**Comment by FinnStutzenstein** [comment]
Context canceled https://github.com/OpenSlides/openslides-client/issues/317
