### ISSUE TITLE
list_of_speakers slide

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#256]

**Comment by FinnStutzenstein** [comment]
TODO:
- The speaker format is not up-to-date (see the version in the wiki)
- last speakers are not limited to `meeting/list_of_speakers_amount_next_on_projector`; the next speakers I didn't test, maybe the same issue there.
- The title information for topics is a string. I get `"title_information for topic/1"` from the server

**Comment by FinnStutzenstein** [comment]
Maybe @r-peschke can do this?

**Comment by FinnStutzenstein** [comment]
- My bad: There is a new field for the LOS slide: `number_of_last_speakers`. I completely oversaw a setting.
- I miss an autoupdate: If I project the LOS for a topic and I change the `item_number` from the topic's agenda_item, the autoupdate is missing. I would expect to get one since the `item_number` is part of the `title_information` of a topic. This is maybe a more generic problem, but this is the first place I noticed it.

**Comment by r-peschke** [comment]
>     * I miss an autoupdate: If I project the LOS for a topic and I change the `item_number` from the topic's agenda_item, the autoupdate is missing. I would expect to get one since the `item_number` is part of the `title_information` of a topic. This is maybe a more generic problem, but this is the first place I noticed it.
Do you need the item number always? The current implementation fills it only, if you get the title in the context of an agenda_item_list. In all other cases the item number is always empty. It seems that I have to change it;-)

**Comment by r-peschke** [comment]
I'm on the number_of_last_speakers. What's about the number of waiting speakers? They can also be limited and might be more interesting than the number of finished speakers

**Comment by FinnStutzenstein** [comment]
The amount is not shown on the slide, so there is (currently*) no need for the number of waiting speakers.

*As aloways: Might change in the future, but currently not needed.

**Comment by r-peschke** [comment]
Filling the item number in GetTitleInformation for motion, motion_block, topic and assignment outside from AgendaItemList context is still missing
