### ISSUE TITLE
Provide a "single-shot"-route

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#260]
Provide a "single-shot"-route, which accepts a usual request from the client and sends as response directly the data.
A "normal" request/response-pattern...

Needed for issues like OpenSlides/openslides-client#355.

**Comment by ostcar** [comment]
Could you explain to me why it is not possible to use the "live" request and close it after the first response?

**Comment by GabrielInTheWorld** [comment]
> Could you explain to me why it is not possible to use the "live" request and close it after the first response?

We discussed this in our team and decide, that this is a task for the AU-service. The reason is, that it is only a "small" work to implement this feature in the AU-service. But for the client it is a "big" work to implement such a feature.

**Comment by ostcar** [comment]
Ok. Should not be to hard. I can do it.

**Comment by ostcar** [comment]
How urgent is this? I could add this with a quick fix, but as I looked at the code, it could need some cleanup to solve this in a better way.

**Comment by GabrielInTheWorld** [comment]
Take time and solve this in a better way. At the moment, we can workaround it.

**Comment by ostcar** [comment]
@GabrielInTheWorld This PR adds a way for a single_shot: https://github.com/OpenSlides/openslides-autoupdate-service/pull/309

With this commit, the request ends after the first data, if you add the query "single" to the url.

```
curl localhost:9012/system/autoupdate?single=true -d '[{"collection":"meeting","ids":[1],"fields":{"enable_anonymous":null}}]'
```

But I am not sure what api would be the best. Should I add another url?

I also provide an url where you can send a get requst with a list of fqFields. The result is the same as the normal autoupdate-url. Of cause, relations are not handled. For example the request above is the same as:

```
curl localhost:9012/system/autoupdate/keys?meeting/1/enable_anonymous
```

It would be nice if the `signle`flag could also be used on this url. Should I change it to `/system/autoupdate/keys?k=fqfield1,fqfield2,...`? Then it would be possible to add the `signle`flag.

Or should `signle` be the default and the flag `live` or `autoupdate` enalbes the autoupdate?

What do you think?

**Comment by ostcar** [comment]
Ok. I have a version that I like.

With #309, there is only one handler (`/system/autoupdate`). You can use it as before as a post-request with a body.

But it is also possible to additional request keys with `/system/autoupdate?k=fqfield1,fqfield2...`. A request can have both. The query and the body. In this case, all keys are requested.

With the query-paramenter `single`, the handler returns after the first data.

So the client can add `?single=true` to the url to get a single-shot url
