### ISSUE TITLE
Add calculated field `access=true` to meetings

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#277]
It should be places in group B for the restrictions.

**Comment by ostcar** [comment]
Please tell me more about. Why is it necessary? How do I calculate it?

**Comment by FinnStutzenstein** [comment]
Just add the field `access` with the value `true`. It is needed by the client to check, if specific fields can be fetched to determinate whether the client can access the meeting next to seeing the meeting (access and see is different - this is new in OS4)

**Comment by ostcar** [comment]
Why is it not possible to access another field from group B? For example the description?

**Comment by FinnStutzenstein** [comment]
Since it is a misuse of this field.

**Comment by ostcar** [comment]
You could say the same about adding a calculated field that is not calculated.

I don't want to add code (and possible bugs) if there is another easier way to solve this.

If you still think, that this field is necessary, then please reopen this issue and talk about via telephone with the core team.
