### ISSUE TITLE
User with `CML.can_manage` or `OML.can_manage_organization` cannot see meetings

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#287]
If a user has the permission `OML.can_manage_organization` and has not created meetings, they cannot see these meetings. This is also the case, if they have the permission `CML.can_manage` for any committees. (Then, they cannot see meetings inside these committees)

I see, that this user gets the names of all meetings, but no description or other related information of the meetings, like seen below:
![member-list-not-seen](https://user-images.githubusercontent.com/10206688/127671067-80a7a25d-0cab-4046-8099-9612929efdb2.png)

The expected behavior is, that users with the `OML.can_manage_organization` can see all meetings due to the fact that they can edit those meetings. Users with the `CML.can_manage` can at least see every meeting inside their related committee.

**Comment by ostcar** [comment]
You are right, that there is a bug. But I don't know you are right, that users with OML.can_manage_organization or CML.can_manage can see all fields

https://github.com/OpenSlides/OpenSlides/wiki/meeting-restrictions

In the wiki it says, that you need the OML.superadmin to access a meeting.

With the CML.can_manage, you have to see-property, but can not see the fields in Group C and D.

Is the wiki correct?

**Comment by FinnStutzenstein** [comment]
Yes, with OML `can_manage_organization`, the user implicitly has CML `can_manage`, so the user can see groups A and B

**Comment by ostcar** [comment]
> Yes, with OML `can_manage_organization`, the user implicitly has CML `can_manage`, so the user can see groups A and B

Is this documented anywhere? This is the only place where this is relevant. Would it not be easier to document is explicit at the meeting-restrictions page?

Are there other implicit permissions that I should know about?

**Comment by FinnStutzenstein** [comment]
Everything permission related is documented here: https://github.com/OpenSlides/OpenSlides/wiki/Permission-System#organization-management-level-oml

**Comment by ostcar** [comment]
Is it ok that I remove this sentence from the wiki page `Users with the OML at least can_manage_organization have automatically all committee management levels.`

As written above. There is only one place where this is relevant. I would be easier to read, if this rule would be documented at this one place instead of another wiki page. Even in the permission-system wiki-page it is not possible to see, where this rule is relevant.

**Comment by FinnStutzenstein** [comment]
This won't delete the rule and this is the brief overview, so it is ok  (There is still `A user with can_manage_organization is indirectly a committee manager for every committee`)

> There is only one place where this is relevant. I would be easier to read, if this rule would be documented at this one place instead of another wiki page

I do not know what you mean. This rule is also needed in the client and the actions also need it. It's implemented in both systems. We talked month ago about the permission system and fixed it. There is no need of redoing it now.

**Comment by ostcar** [comment]
I fixed this for this case. Since there is no other case, a general solution that oml can manage is also cml can manage is not necessary.

**Comment by tsiegleauq** [comment]
> `Users with the OML at least can_manage_organization have automatically all committee management levels.`

This information is most likely not required in the overview. The first section is more like a lengthy table of contents.

The information

> `A user with can_manage_organization is indirectly a committee manager for every committee. `

Is then already covered in the first section.
So removing the explanation in the overview is okay.
