### ISSUE TITLE
Use new example data format

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-autoupdate-service#296]
Does this service use the example-data.json from the main repository?

If yes, it should mention the new format: https://github.com/OpenSlides/OpenSlides/pull/6203

**Comment by ostcar** [comment]
Thanks for the info. I use the example data not in this repo but in the models-to-go repo.

The example data file is only read at code generation time. If you merge you pr, it will not break the autoupdate service.

Please ping me again when you merged your pr
