### ISSUE TITLE
`is_active_in_organization_id` is filtered for users with `OML.can_manage_organization` or lower

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#319]
Users with the `OML.can_manage_organization` do not see, which meeting is active or archived.

**Comment by ostcar** [comment]
Which field decides if a meeting is archived?

Could you (as always) paste the query to the autoupdate service?

**Comment by GabrielInTheWorld** [comment]
> Which field decides if a meeting is archived?

There is a field in every meeting-model called `is_active_in_organization_id`. If this field is set to `0` or `None`, then a meeting is archived. If this field is set to a positive number, then a meeting is active (not archived).
> 
> Could you (as always) paste the query to the autoupdate service?

```js
[
  {
    "collection":"meeting",
    "fields":{
      "description":null,
      "name":null,
      "start_time":null,
      "end_time":null,
      "is_active_in_organization_id":null,
      "user_ids":null,
      "organization_tag_ids":null,
      "location":null,
      "id":null
    }
  }
]
```

**Comment by ostcar** [comment]
I found the "bug". Fields where added to the models.yml but nobody informed me about it.

#320 fixed this.

**Comment by ostcar** [comment]
@GabrielInTheWorld There should have been log messages from the autoupdate service, that the models.yml seems to old and that `go generate ./...` has to be called. Can you confirm that there were these log messages?

**Comment by GabrielInTheWorld** [comment]
> @GabrielInTheWorld There should have been log messages from the autoupdate service, that the models.yml seems to old and that `go generate ./...` has to be called. Can you confirm that there were these log messages?

Yes, I can confirm this. I have sometimes seen this message.
