### ISSUE TITLE
Normal user gets no poll result

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-autoupdate-service#334]
* Create a new motion poll (e.g. named voting) as admin for delegates and admins
* start voting
* vote with admin user
* vote with delegate user
* stop and publish voting as admin
=> delegate user gets incomplete vote result! Yes/No/Abstain is empty (no autoupdate). Valid votes are available only. 
* open detail view of motion poll: single votes and entitled users are succuessfully visible in both list.

**Comment by GabrielInTheWorld** [comment]
Okay, after some more investigation, I found the bug:
The data
```json
{
    "option/16/abstain": "5.000000",
    "option/16/no": "5.000000",
    "option/16/yes": "5.000000"
}
``` 
came only after adding a user from group `delegates` to the group `admin` in a meeting. That means, in @emanuelschuetze's post, the keys `option/22/abstain`, `option/22/yes` and `option/22/no` are missing.
