### ISSUE TITLE
Send new field limit_of_users 

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-autoupdate-service#352]
Please send the new field `limit_of_users`, which is required in settings for superadmin only. Currently, you can test it by input the value but it was not shown correctly after reload the page.

backend implementation:
https://github.com/OpenSlides/openslides-backend/pull/999

client implementation:
https://github.com/OpenSlides/openslides-client/pull/601

**Comment by GabrielInTheWorld** [comment]
I think, this is resolved by OpenSlides/openslides-client#604.
