### ISSUE TITLE
impacts of moving models.yml etc. from openslide to backend

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-autoupdate-service#360]
The files models.yml, permission.yml, initial-data.json and example-data.json are moved from openslides-repo to openslides-backend-repo.
This issue tries to redirect all relations from autoupdate-service to the backend.

Related Issues:
https://github.com/OpenSlides/OpenSlides/pull/6270 deletes the files in openslides-repo
https://github.com/OpenSlides/openslides-backend/issues/1008 related backend issue
https://github.com/OpenSlides/openslides-backend/pull/1009 related backend pull request

**Comment by ostcar** [comment]
I already prepared that change. It `should` work only to updates this values here: https://github.com/OpenSlides/openslides-autoupdate-service/blob/3881ac01b5b11020ec3f92ddf1b1c47b888c8f30/internal/models/models.go#L33-L38

If you like, you can create a PR or we change this when the models.yml changes for the next time.

If you change the values, please run `go generate ./...` to check, that there are no errors.
