### ISSUE TITLE
The AU-service does not send information about an active-meeting at the fullscreen-projector

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#376]
Steps to reproduce:

1. Open a projector in fullscreen-mode
2. Open the dev-console
3. You should see, that a request to the AU-service was opened, but no updates for this request came to the client

**Comment by ostcar** [comment]
I will try to reproduce it as soon as possible (probably not today). But this bug sounds very strange. The autoupdate-service does not even know if the browser is in fullscreen-mode.

Are there any log messages from the autoupdate-service? (Only errors are logged)

Could you paste the request body?

**Comment by ostcar** [comment]
I can not reproduce this.

I am not absolutely sure what you mean with "open projector in fullscreen-mode". You mean open the url https://localhost:8000/1/projector/1 ?

On the console I see two javascrip tracebacks. But I don't know how to read them or how they correspond to the autoupdate update response.

So I need more infos to help you here

**Comment by ostcar** [comment]
@GabrielInTheWorld Can you confirm that this bug still exists and if it does exist tell me step by step what I have to do to reproduce this?

**Comment by GabrielInTheWorld** [comment]
No, it seems to be resolved.
