### ISSUE TITLE
vote_count poll can only increaes

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-autoupdate-service#389]
When many votes are counted at the same time, there could be a race conition, that an lower vote_count value is received after a higher value. In the end, the vote_count can be to low.

To fix this, the autoupdate-service should only use new values, when they are higher as the old ones. But if a vote gets resettet, then the value 0 has to be used again.

**Comment by emanuelschuetze** [comment]
This is important for admin users. Can you provide a fix?

**Comment by ostcar** [comment]
This should be fixed with #407

But you have to update the autoupdate-service and the vote-service at the same time!
