### ISSUE TITLE
The AU-service does not recognize previous `vote_count`s

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#410]
I have two users and one election. One of these users is present, the other not.
I started the election and vote with the present user. After that, I toggle the other user's presence to "be present".
Then, the `vote_count` for the election goes down to `null`. See the picture:

![AU_not_recognizing_old_vote_counts](https://user-images.githubusercontent.com/10206688/152141287-7d4c3ef4-3dc6-45c8-9771-5bf2c48ef909.png)

**Comment by ostcar** [comment]
I can not reproduce this.

I created a new meeting with a new user as delegated. I also created a new motion and a new motion-poll.

Then I logged in as superadmin and set the state to present. 

Then I logged in as the new user with state to not present.

Then I voted as superadmin. It shows "1/1 users have voted.

Then I set the state of the other user to present. The message changes to "1/2 users have voted".

Can you make sure, that you are using the newest version of the autoupdate-service and the vote-service? I merged updates of both services that can only be used together.

Can you also check, if there are any error messages on the server log of the autoupdate-service or vote-service?
