### ISSUE TITLE
Ensure that at least committee_managers see every meeting marked as `template_meeting` in other committees

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#414]
There is the relation `template_meeting_ids` in the `committee`-collection (after OpenSlides/openslides-backend#1193 is resolved). At least every committee_manager (who can create meetings) should see meetings in this relation from other committees, although they are not registered as managers in those committees. (if this is not already the case)

**Comment by ostcar** [comment]
If I understand you correctly, you want to change the `meeting can see`property. The current rules are defined here:

https://github.com/OpenSlides/openslides-autoupdate-service/blob/31116118322be576baf661badce57f88e782df52/internal/restrict/collection/meeting.go#L13-L17

But I did not understand which case you want to add.

Can you complete this sentence for your new case:

>  The user can see a meeting if ....

**Comment by GabrielInTheWorld** [comment]
> A user can see a meeting, if they are registered as committee_manager and the meeting is registered in `template_meeting_ids` for any committee.

**Comment by ostcar** [comment]
To translate this to the fields in the models.yml you mean:

The use can see a meeting, if the field `user/committee_$can_manage_management_level` is not empty and `meeting/template_meeting_id` is not null (after the linked commit `meeting/template_meeting_ids` is not empty).

Is this correct?

**Comment by GabrielInTheWorld** [comment]
It is `meeting/template_for_committee_id` and `committee/template_meeting_ids`, but yes, this sounds correct.
