### ISSUE TITLE
The field `committee/template_meeting_ids` will be changed

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#422]
After we discussed the meaning of the field `committee/template_meeting_ids`, we decided to change this field.
After OpenSlides/openslides-backend#1219 is merged, the field `committee/template_meeting_ids` has been removed and the field `organization/template_meeting_ids` has been introduced. Every user, who has the permission `CML.can_manage` or `OML.can_manage_organization` or higher can see the filed `organization/template_meeting_ids`.
Please make changes accordingly.

**Comment by ostcar** [comment]
Already done
