### ISSUE TITLE
Service should ignore auth_cookie_key and auth_token_key secret in development mode

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-autoupdate-service#425]
At the moment the service uses the secrets if they are present. In dev mode it should ignore the present secrets and use the development defaults.

**Comment by normanjaeckel** [comment]
Alternative: The auth service has to be changed to use the secrets if they are present even in dev mode.

**Comment by ostcar** [comment]
@normanjaeckel do I understand you correctly, that the behaviour of the autoupdate-service and the auth-service is different in dev mode?

@GabrielInTheWorld we should agree on one behaviour. I have no favour. Is it correct, that the auth-service ignores the secrets in dev mode and always uses the dev keys? I can do the same.

One advantage of the current behaviour of the autoupdate service is, that it is possible to test different auth-keys in dev mode. But if we never do this, then this is nor important.

@GabrielInTheWorld Please make a decision if I should change the go-auth-code or if you changes the typescript- and python-auth-code

**Comment by normanjaeckel** [comment]
Yes. The behavior is not unified at the moment so I can not start the production setup with `OPENSLIDES_DEVELOPMENT=1` (so see some more logs) because of this issue.

**Comment by ostcar** [comment]
@GabrielInTheWorld ping

**Comment by ostcar** [comment]
Since we get no feedback from @GabrielInTheWorld, the easiest way to fix with would be, that the autoupdate-service implements the behavior of the auth service.

But I am not sure if this could be a security problem. If a user activates the development mode in production to get more log messages (he should not do this, but he could), then insecure auth tokens would be created. So even when you activate the dev mode only for one minute, an attacker could easily create a valid auth token for user_id=1 and create a new admin account that would be valid after the dev-mode was disabled again.

So I think the current behavior of the auth service is dangerous and should be changed.

**Comment by GabrielInTheWorld** [comment]
> @GabrielInTheWorld we should agree on one behaviour. I have no favour. Is it correct, that the auth-service ignores the secrets in dev mode and always uses the dev keys? I can do the same.
> 
Yes, the auth-service ignores any other secrets than the dev secrets.

> One advantage of the current behaviour of the autoupdate service is, that it is possible to test different auth-keys in dev mode. But if we never do this, then this is nor important.
> 
> @GabrielInTheWorld Please make a decision if I should change the go-auth-code or if you changes the typescript- and python-auth-code

We should implement the same behavior in every service. So, please adjust the autoupdate-service to use only dev secrets in the dev setup.

**Comment by GabrielInTheWorld** [comment]
> Since we get no feedback from @GabrielInTheWorld, the easiest way to fix with would be, that the autoupdate-service implements the behavior of the auth service.
> 
> But I am not sure if this could be a security problem. If a user activates the development mode in production to get more log messages (he should not do this, but he could), then insecure auth tokens would be created. So even when you activate the dev mode only for one minute, an attacker could easily create a valid auth token for user_id=1 and create a new admin account that would be valid after the dev-mode was disabled again.
> 
> So I think the current behavior of the auth service is dangerous and should be changed.

This is not dangerous and won't be changed, because in the dev setup we will use dev secrets.
