### ISSUE TITLE
Exit code on normal shutdown

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-autoupdate-service#434]
When I run this service in the default docker compose setup provided by the manage tool with `docker-compose up` and I later hit `Ctrl+C` the service (and also all other Golang services) exit with error code `2`. (datastore and auth exit with 137, all other with 0). I would expect 0. What can we do?

**Comment by ostcar** [comment]
Currently, the service is listening on os.Interrupt: https://pkg.go.dev/os#Signal

In your case, docker probably sends the term signal. To catch it, it is possible to listen to `syscall.SIGTERM`. See https://gobyexample.com/signals

But there are problems with the syscall package: https://pkg.go.dev/syscall#pkg-variables

But for the OpenSlides usecase, it might be ok.
