### ISSUE TITLE
A mediafile without `access_groups` resctrictions are not shown to everyone

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#435]
Only administrators see them.
If the field `access_groups` of a mediafile is empty, every user in the same meeting as the mediafile should see the mediafile.

**Comment by ostcar** [comment]
I need more information.

The current restriction for mediafiles is this one: https://github.com/OpenSlides/openslides-autoupdate-service/blob/bda412e15108b533be4bad38ed4c5f98dde2102f/internal/restrict/collection/mediafile.go#L13-L20

Are you sure this should be changed? Why shut a mediafile that has `mediafile.public=false` be shown to everyone? @emanuelschuetze what do you think?

**Comment by GabrielInTheWorld** [comment]
> Are you sure this should be changed? Why shut a mediafile that has `mediafile.public=false` be shown to everyone?

First of all: Why would the field `public` be `false` if none access group is set?

**Comment by ostcar** [comment]
> > Are you sure this should be changed? Why shut a mediafile that has `mediafile.public=false` be shown to everyone?
> 
> First of all: Why would the field `public` be `false` if none access group is set?
The two field are separate. I assumed that in your case `public` is `false`. If it is `true`, then the fields should be visible to everybody.

In your usecase, is the field `public` `true` or `false`?

**Comment by emanuelschuetze** [comment]
Fixed in backend. Works now.
