### ISSUE TITLE
Current `main` is unstable

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#458]
The current `main` branch lets crash the building of the autoupdate docker-container with the following error:
```
docker-autoupdate-1        | Error while building:
docker-autoupdate-1        |  cmd/autoupdate/main.go:23:2: no required module provides package golang.org/x/sys/unix; to add it:
docker-autoupdate-1        | 	go get golang.org/x/sys/unix
docker-autoupdate-1        |
```

I think, the commit #454 has this impact.

**Comment by ostcar** [comment]
I can not reproduce it. It works fine for me. Can you tell me exactly what you did? 

I tried building the docker container in the repo:

```
docker build .
```

I tried starting the full dev mode in the main repo

```
make services-to-main
make run-dev
```

Both worked. How exactly did you build the container?

**Comment by GabrielInTheWorld** [comment]
```
make stop-dev
docker system prune --volumes
./services-to-main.sh -p
make run-dev
```

**Comment by ostcar** [comment]
I did this and it still works for me. Do you have another idea how I can reproduce this?

**Comment by GabrielInTheWorld** [comment]
Hmm... Well, then I will close this issue until it is necessary again.
