### ISSUE TITLE
History didn't display motions

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-autoupdate-service#528]
When opening a motion in the chronicle, no content is displayed, but an error message appears. 

Error occurs in instance https://tis.openslides.com/5/history. It affects all meetings in the instance. Instance is on update status OpenSlides Version: 4.0.0-beta-20220622-2b43093. 

Can't find error in other instances. Unclear if error occurs in other instances or is solved by newer updates.

What should happen: History an used without errors.

![Screenshot_20220718_093748](https://user-images.githubusercontent.com/105491030/179464537-d197cc65-e65b-4e7b-9747-d953a9e72a2a.png)

**Comment by jsangmeister** [comment]
It seems like there is a bug in this code part: https://github.com/OpenSlides/openslides-autoupdate-service/blob/22990efce691034505187a54d3dd8cb8ebdf02fd/internal/autoupdate/autoupdate.go#L211-L231

If I understood it correctly, `hasMeeting` refers to the object being requested. So, if it has a meeting id (like a motion has), it is checked afterwards if the requesting user has the right permission in the meeting. There, the check is missing if the user is superadmin so he can see the history (or just put the check before the whole `if` block).

@MSoeb I'm assuming if you try to access the history with a meeting admin or meeting user which has the correct permissions, this should work.
