### ISSUE TITLE
Meeting admins should be able to see forwarded motions when `is_submitter` restriction is set

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-autoupdate-service#625]
As a meeting admin only part of a motion is sent to the client for forwarded motions if only the `is_submitter` restriction is set within the workflow. This makes no sense and results in the client not being able to display all the motion information. 

The original issue is https://github.com/OpenSlides/openslides-client/issues/1979

**Comment by ostcar** [comment]
This is a duplicate of https://github.com/OpenSlides/openslides-client/issues/1979. If there is something to do in the autoupdate service to fix the issue, then please transfer the issue in the autoupdate repo.
