### ISSUE TITLE
Restrict amendments if lead motion is also restricted

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-autoupdate-service#641]
Will fix bug described in OpenSlides/openslides-client#2082

Amendments are to be differentiated from other motions by virtue of having a `lead_motion_id`

If a motion A has a `lead_motion_id` referencing a motion B (i.e. if A is an amendment to B) and the request user does not have the right to see B, he should also not be allowed to see A.

Please change the restrictor so that this is the case

**Comment by ostcar** [comment]
I can do this.

How quickly do you need this? Is it ok for you, that I wait, until the feature branch for template fields is merged?

**Comment by luisa-beerboom** [comment]
> I can do this.
> 
> How quickly do you need this? Is it ok for you, that I wait, until the feature branch for template fields is merged?

@rrenkert Could you answer this question?

**Comment by jsangmeister** [comment]
@ostcar if it's not too much work, it would be nice to have this before the template field removal is finished, since we don't know how long this will take.
