### ISSUE TITLE
Restrict hidden topics

### ISSUE THREAD

**Issue by rrenkert** [OpenSlides/openslides-autoupdate-service#644]
**Reproduction**
* Create a hidden topic item as meeting admin
* Open the new topic and save the URL somewhere
* Logout
* Login as delegate
* Paste the topic URL

-> the topic is visible

The autoupdate-service should restrict the topic if it is hidden.

**Comment by ostcar** [comment]
I found the problem. The restricter checks the hidden state only for the `agenda_item`-collection but not for the `topic`-collection.

https://github.com/OpenSlides/openslides-autoupdate-service/blob/9b5848b44cbbe770e0cedbc8591e0aeb07409ed5/internal/restrict/collection/topic.go#L11-L15

The topric-restricter has to be changed, that a topic can only be seen, when the linked agenda_item can be seen. This is an easy fix. I can do it in the next days.
