### ISSUE TITLE
Reduce autoupdates for projections

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-autoupdate-service#679]
Currently, all users which have the permission `projector.can_see` get autoupdates for all projection in the preview or history of all projectors. This is unnecessary or even unwanted data being sent to all such users, since e.g. all motions which have been projected at one point in time will be sent to all users if the motion text changes.

Proposed changes:
- projections in the preview or history of a projector (so, without `current_projector_id` set) should only be sent to users with `projector.can_manage`
- the `content` field of such projections can be reduced to only the necessary data, since the client does not display the full projection in the preview/history, but only the title. @bastianjoel @luisa-beerboom maybe you can give more input here which fields are needed for preview/history, if necessary on a per-collection basis.

**Comment by bastianjoel** [comment]
This is already prepared in the client and only needs to be defined in `projectors.subscription.ts`. The fields `preview_projection_ids` and `history_projection_ids` already do not have a fieldset defined and therefore throw a `Non explicit use of default fieldset`. Someone just needs to check which fields are required. 
Within the autopilot the history and preview slides are already not requested anymore.

**Comment by ostcar** [comment]
As discussed: The client does not need the field projection/content when `current_projection_id` is nil.

I will implement this. Afterwards the client has to be updated to create the title for old projections.

**Comment by luisa-beerboom** [comment]
What is the title calculated from?
Because if it is not calculated from the projection data that comes from the autoupdate, I would consider that to be a mistake

**Comment by jsangmeister** [comment]
It is calculated from the content object via the method `getProjectionTitle()` or something alike. This is the right way, I think - the autoupdate service should not control how the client displays content.
