### ISSUE TITLE
Extend `restrict_fqids` endpoint `fields`

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-autoupdate-service#710]
For the search service we want a way to retrieve relations from the `restrict_fqids` endpoint. 

I suggest extending the `fields` field to have the same functionality as the `autoupdate`s endpoint. 

An example request could look as following:
```json
{
    "user_id": 1,
    "fqids": ["...", ...],
    "fields": {
        "poll": {
            "id":null,
            "sequential_number":null,
            "content_object_id":{
                "type":"generic-relation",
                "fields":{
                    "title":null,
                    "sequential_number":null,
                    "meeting_id":null,
                    "id":null
                }
            }
        }
    }
}
```

**Comment by ostcar** [comment]
Would it be possible to use the autoupdate endpoint? Maybe with an internal route, that allows for a Get-variable, or http-header to specify the user_id.

For example:
``` json
[
  {
    "collection": "motion",
    "ids": [...],
    "fields": {
        [...]
    }
  },
  {
    "collection": "poll"
    "ids": [..],
    "fields": {
        "id":null,
        "sequential_number":null,
        "content_object_id":{
            "type":"generic-relation",
            "fields":{
                "title":null,
                "sequential_number":null,
                "meeting_id":null,
                "id":null
            }
        }
    },
   [...]
]
```

**Comment by bastianjoel** [comment]
Yes, I think that would work.

**Comment by ostcar** [comment]
Ok. Then I will create a PR where I add the internal route, where you can specify a user ID and remove the other search specific code.

**Comment by bastianjoel** [comment]
I just noticed that the response format of the autoupdate route is different. Would it be possible to keep the current format of the `restrict_fqids` endpoint or would that be too complicated?

**Comment by ostcar** [comment]
I would like to keep the output format the same. The reason is, that I am thinking about changing the autoupdate format (not in the near future). Maybe to something like GraphQL. This is easier, when there are no special cases.

But it should be very easy to transform the format in the searchservice. This is the current converter code. You can use this in the search service:

https://github.com/OpenSlides/openslides-autoupdate-service/blob/65596467e838f3906556f79c6a3586d116b2a188/internal/autoupdate/autoupdate.go#L307-L319C3

**Comment by ostcar** [comment]
This is my idea: https://github.com/OpenSlides/openslides-autoupdate-service/pull/721

Do you think, you can work with that?
