### ISSUE TITLE
Adjust Autoupdate-service for point of order categories

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-autoupdate-service#713]
See the following backend issue and pull request: OpenSlides/openslides-backend#1774 and OpenSlides/openslides-backend#1785

There are some new fields and a new collection `point_of_order_category` that needs to be added to the restrictor.

The point of order category model has only one restriction mode `A` and it should be restricted as follows:
- Anyone who can see the point of order category should be able to see it

**Comment by ostcar** [comment]
The changes to the models.yml have to be pushed to main before I can start with this change. It can be done in a separate Backend PR.

I don't understand, how the  `point_of_order_category` should be restricted. You say, anyone who can see point_of_order_category, can see the point_of_order_category. This sentence is true, but not helpful :D

**Comment by jsangmeister** [comment]
Extracted the model changes in https://github.com/OpenSlides/openslides-backend/pull/1798 - since everything about the new feature is optional, I see no problem in merging it.

**Comment by ostcar** [comment]
Ok. For the restriction module, there are only the restriction mods. There is no visibility of a collection.

So you want to say:

Anyone who can see the meeting linked in point_of_order_category/meeting_id can see the point_of_orderder category

Got it

**Comment by rrenkert** [comment]
The backend changes are merged in https://github.com/OpenSlides/openslides-backend/pull/1785

**Comment by ostcar** [comment]
I see now, that the new collection is part of the `list_of_speaker`-feature. Are you sure, that it should not be related to the permission `list_of_speakers.can_see`?

**Comment by luisa-beerboom** [comment]
From the client's point-of-view it presents as a setting, so it should be, at the very least, visible to everyone who can edit the settings (`meeting.can_manage_settings`) and everyone who can see the list of speakers.

If you'd like you can restrict it as such, but honestly, I don't think it makes much of a difference.
