### ISSUE TITLE
Autoupdate service currently doesn't work in conjunction with client

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-autoupdate-service#75]
How to reproduce:
- check out 64628e4be90f3b7bdcba8f88792f705ebe8afd54 on openslides4-dev in the main repo (https://github.com/OpenSlides/OpenSlides/pull/5458)
- update `openslides-autoupdate-service` to current master
- `make run-dev`
- open agenda or any other list view -> no data is displayed

**Comment by ostcar** [comment]
Would it be possible that you construct the http request to the autoupdate service as a curl command and print it here? Then I can test the issue without the client and can be sure that this is an error with the autoupdate service and not from the client.

**Comment by jsangmeister** [comment]
curl localhost:9012/system/autoupdate -d '[{"collection":"meeting","ids":[1],"fields":{"agenda_item_ids":{"type":"relation-list","collection":"agenda_item","fields":{"item_number":null,"comment":null,"closed":null,"type":null,"is_hidden":null,"is_internal":null,"duration":null,"weight":null,"level":null,"parent_id":null,"child_ids":null,"meeting_id":null,"content_object_id":{"type":"generic-relation","fields":{"title":null,"number":null,"list_of_speakers_id":{"type":"relation","collection":"list_of_speakers","fields":{"closed":null,"speaker_ids":{"type":"relation-list","collection":"speaker","fields":{"begin_time":null,"end_time":null}}}}}}}}}}]'

This is the request issued by the client when opening the agenda. The autoupdate service seemingly goes into an infinity loop, there's no answer, even when started alone with the datastore.

**Comment by ostcar** [comment]
I probably added a deadlock in #73. I will fix this as soon as possible.

For the meantime, the commit before #73 should work.

**Comment by ostcar** [comment]
Thanks for reporting the issue and for giving the curl command. With the curl-command it was easy to find the bug.
