### ISSUE TITLE
Change profile routes to be internal

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-autoupdate-service#765]
We want to gather some profile data. But the fact it is atm publicly served when enabled is concerning.

Please change the routes to be internal such that it will not get routed by the proxy.
We will then get the profiles by `curl`ing them from inside the stack or something similar.

**Comment by ostcar** [comment]
I can do this.

In this case, there is no need to activate the profiling routes via an environment varialbe. All the variable does is adding the route. The profiling code is in the go runtime anyway.

Is this ok for you?

**Comment by peb-adr** [comment]
Well yeah I guess it would be okay then..
@rrenkert speak up if you're against this ;)

**Comment by rrenkert** [comment]
Already talked to @ostcar. That's ok for me!
