### ISSUE TITLE
Fix vanishing motion-number (Bezeichner) in agenda

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-autoupdate-service#772]
**Current behaviour:**
If the motion-number (Bezeichner) is not preloaded while entering the agenda then the number is not displayed: 

A) Agenda with preloaded motions:
![Screenshot_20230904_091943](https://github.com/OpenSlides/openslides-client/assets/69210919/5da11190-8eff-4e5c-8ef2-38256e3b8d5c)

B) Agenda without preloaded motion:
![Screenshot_20230904_092311](https://github.com/OpenSlides/openslides-client/assets/69210919/8d5aa6f5-69b3-49c5-9178-6cb75b3915e3)

**Reproduction:**
1. create a motion 
2. make sure the motion has a number (Bezeichner)
3. add the motion to the agenda
4. open the Agenda (you should see something similar to A) )
5. reload the page (now you should see something similar to B) )

**Wanted behaviour:**
The motion-number (Bezeichner) should be displayed without having to preload the motions

**Comment by bastianjoel** [comment]
This issue is very similar to https://github.com/OpenSlides/openslides-client/issues/2739 where fields of a `generic-relation` were not returned too. This is reproducible with the example data from the backend repo when requesting the agenda list subscription used by the client. Only two of four motion numbers get returned. 

Subscription:
```json
[{"collection":"meeting","ids":[1],"fields":{"projector_countdown_default_time":null,"agenda_item_ids":{"type":"relation-list","collection":"agenda_item","fields":{"id":null,"item_number":null,"comment":null,"closed":null,"type":null,"duration":null,"is_internal":null,"is_hidden":null,"level":null,"weight":null,"content_object_id":{"type":"generic-relation","fields":{"number":null,"title":null,"agenda_item_id":null,"sequential_number":null,"meeting_id":null,"id":null,"list_of_speakers_id":{"type":"relation","collection":"list_of_speakers","fields":{"closed":null,"sequential_number":null,"meeting_id":null,"id":null,"speaker_ids":{"type":"relation-list","collection":"speaker","fields":{"begin_time":null,"end_time":null,"id":null,"point_of_order_category_id":{"type":"relation","collection":"point_of_order_category","fields":{"id":null,"text":null,"rank":null,"meeting_id":null,"speaker_ids":null}}}}}}}},"parent_id":null,"child_ids":null,"tag_ids":null,"projection_ids":null,"meeting_id":null}},"tag_ids":{"type":"relation-list","collection":"tag","fields":{"name":null,"meeting_id":null,"id":null}}}}]
```

**Comment by ostcar** [comment]
This should be fixed with https://github.com/OpenSlides/openslides-autoupdate-service/pull/780

Without the fix, I can reproduce this. With the fix, I can not reproduce it anymore.

Please reopen, if you can reproduce it with the current master
