### ISSUE TITLE
Projector content not updated after cache reset

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-autoupdate-service#775]
After a cache reset the projector content of e.g. countdown do not get updated anymore.

**Comment by bastianjoel** [comment]
Connections that were open previous to the cache reset still do not receive data after cache reset.

**Comment by ostcar** [comment]
I can not reproduce this.

I started the service with `CACHE_RESET: 10s` and even added some logging to see, that the cache really gets resetted.

Then I created two topics and projected them alternated, after a cache reset. Everything works fine.

Even when I reset this change https://github.com/OpenSlides/openslides-autoupdate-service/pull/776, everything works fine for me.

Can you tell me what I have to do to reproduce this?

**Comment by bastianjoel** [comment]
We did this with the countdown slide.

**Comment by ostcar** [comment]
What exactly did you do?

1. Start the countdown. 
2. Wait until the cache reset
3. Stop the countdown
4. Wait until the cache reset
5. Start the countdown again

Everything works for me

**Comment by bastianjoel** [comment]
As far as I remember we did the following:
1. Project countdown (do not start)
2. Wait for cache reset 
3. Start the countdown

After that we had did not receive the countdown start on a connection that was opened prior to the cache reset. 
But I guess this is the same as in step 3.-5.. I will try to reproduce this on monday and give you more detailed feedback.

**Comment by bastianjoel** [comment]
I cannot reproduce this either. @peb-adr @m-schieder could you give any more info on how to reproduce?

**Comment by jsangmeister** [comment]
Can this be closed? @peb-adr @m-schieder @bastianjoel

**Comment by m-schieder** [comment]
We were observing this behavior during an event and it coincided perfectly with the cache reset. Since then I have not heard that this has happened again. As we don't know exactly how we can reproduce it, I think the issue can be closed. We can open it again when it reappears.
