### ISSUE TITLE
Better error response for malformed requests

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-autoupdate-service#79]
```js
[
  {
    collection: "topic",
    ids: ["1"],
    fields: {
      title: null,
      text: null,
    },
  },
];
```

Will cause an Error 400, because "1" is a string (and not 1, a number).
In this case, I would like to get better errors to hint what might be wrong, what is missing, and perhaps why it is missing.
Simply ending up with "Bad request" causes some confusion.

**Comment by ostcar** [comment]
From the code, I would expect an error message.

Is this issue, that there is no error message at all or is the issue, that the error message is not good enough?

If it is possible, could you post a curl request and the current output. What did you do, what happend, what did you expect?

**Comment by ostcar** [comment]
Could you test, if #80 helped? I already merged it.

**Comment by ostcar** [comment]
Please reopen, if this is still an issue.
