### ISSUE TITLE
Add new user permissions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-autoupdate-service#818]
see https://github.com/OpenSlides/openslides-backend/issues/2122:

The new restriction mode B for users should be the following (adapted from restriction mode A):
```
Y==X
Y has the OML can_manage_users or higher.
There exists a committee where Y has the CML can_manage and X is in committee/user_ids.
X is in a group of a meeting where Y has user.can_see_personal_data.
```

**Comment by ostcar** [comment]
Please ping me, as soon, as there is a merged models.yml

**Comment by jsangmeister** [comment]
@ostcar ping - we know have the meta repo ;)

**Comment by ostcar** [comment]
Then please ping me, when you added the new permission to the meta repo :)

**Comment by jsangmeister** [comment]
@ostcar, https://github.com/OpenSlides/openslides-meta/pull/8/ contains the related models and permission changes. The list of fields for the new restriction mode may be extended soon, but this does not infere with the general implementation.

**Comment by ostcar** [comment]
@jsangmeister I think `There exists a committee where Y has the CML can_manage and X is in committee/user_ids.` and `There exists a meeting where Y has the CML can_manage for the meeting's committee X is in meeting/user_ids.` is the same. `committee/user_ids` is a calculated field. I think, that it contains the user_ids of all meetings of that committee.

**Comment by jsangmeister** [comment]
> @jsangmeister I think `There exists a committee where Y has the CML can_manage and X is in committee/user_ids.` and `There exists a meeting where Y has the CML can_manage for the meeting's committee X is in meeting/user_ids.` is the same. `committee/user_ids` is a calculated field. I think, that it contains the user_ids of all meetings of that committee.

You are right. I copied this from https://github.com/OpenSlides/openslides-autoupdate-service/blob/2f456362c7047ff671160f3d712cfe5aa70dfa5c/internal/restrict/collection/user.go#L20 - could you also remove the duplicate there?
