### ISSUE TITLE
docker: no such file or directory

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-autoupdate-service#82]
Las working commit is "Fix datastore cache on missing keys (#76)" (92ea69bcb07f899474f40834c320650ba506d62c)
Since `fc46b657cb5f9dad16468c7ac9c8b7c8c0368529` up to the current commit, `make build-dev` returns an error.

```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat ~/OpenSlides/openslides-autoupdate-service/docker: no such file or directory
make[1]: *** [Makefile:2: build-dev] Error 1
make[1]: Leaving directory '~/OpenSlides/openslides-autoupdate-service'
fatal: run_command returned non-zero status for openslides-autoupdate-service
```

to reproduce:
`make build-dev` on current master or OpenSlides4

**Comment by ostcar** [comment]
I fixed it in #81. I will speak with Finn on Thursday. Do you need a quick fix in the master? In this case, I will create and merge a separate PR.

**Comment by tsiegleauq** [comment]
I guess I do. I can try to work on #76 for now, but I usually try to work on the most recent versions. Since I am connecting the new autoupdate to the client, I need the current master to build at all times.

**Comment by ostcar** [comment]
I fixed this in master.

Please let this issue open. I want to add a github action, that tests the makefile.

**Comment by ostcar** [comment]
Ok. The important commands that are documented in the readme (for example the two make-targets) are tested now with github actions.

A tipp: The docker-target-builds runs much faster with buildkit: https://docs.docker.com/develop/develop-images/build_enhancements/
