### ISSUE TITLE
Correct HTTP Status for wrong method

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#91]
When connecting with `GET`, `PATCH`, ... a 405 method not allowed should be returned.

**Comment by ostcar** [comment]
I can do this.

Is it ok for you, that GET and POST request are allowed?

The Problem is, that /system/autoupdate is a GET request with a body. In the curl examples, I use the "-d" flag. But this  sends a POST request.

It would make the curl examples more complicated, if a POST request would return a 405 response.

**Comment by FinnStutzenstein** [comment]
`GET` is never used for `/system/autoupdate` since json data must be passed. It would be a misuse of get params to pass json there. GET should not have data in the body, so just using POST is good.

**Comment by ostcar** [comment]
That is not correct. Please have a look at the RFC.

GET can have a body.

POST should only be used, when the request changes something on the server.

The autoupdate request is a read only request and therefore a GET request.

**Comment by FinnStutzenstein** [comment]
It was stated in former versions, that a body in GET should be ignored. THis was canceled out, but GET with a body is not supported everywhere. Especially browsers have their weaknesses:

https://xhr.spec.whatwg.org/#the-send()-method

See this discussion: https://github.com/angular/angular/issues/9927

I cannot send a GET request with a body, so we must use POST here.

**Comment by ostcar** [comment]
Ok. So GET requests to the autoupdate service are recommended, but POST request are also supported.

All other requests get rejected.

What about HEAD requests? For example to check if a request is valid without starting a stream?

**Comment by FinnStutzenstein** [comment]
I never used HEAD requests. They are not really useful in the case of streams (no contentlength, no caching)..
