### ISSUE TITLE
Meeting.create: make duplicate from (optionally) mandatory

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-autoupdate-service#959]
Context: The new setting from the Meta-Issue https://github.com/OpenSlides/openslides-meta/issues/125

For committeeadmins: If this setting is active then only templates should be returned as potential candidates to duplicate a meeting from
For Orgaadmins and superadmins: The displayed list should be the same as before

**Comment by rrenkert** [comment]
Maybe there is nothing to do here, we have to check which subscriptions come from the client for the 'duplicate from' field.
I will ping or close here after clarification.

**Comment by Elblinator** [comment]
The feature indeed didn't need any changes from the autoupdate :)
